# Generated by Django 3.2.8 on 2021-10-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='cet_scorecard',
            new_name='eamcet_memo',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='cet_percentile',
            new_name='eamcet_score',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='hsc_leaving_certificate',
            new_name='inter_memo',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='hsc_percentage',
            new_name='inter_score',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='hsc_passing_certificate',
            new_name='inter_tc',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='jee_scorecard',
            new_name='jee_memo',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='jee_percentile',
            new_name='jee_score',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='phone_no',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='ssc_leaving_certificate',
            new_name='ssc_memo',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='ssc_percentage',
            new_name='ssc_score',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='ssc_marksheet',
            new_name='ssc_tc',
        ),
        migrations.AlterField(
            model_name='application',
            name='course',
            field=models.CharField(choices=[('Computer Science Engineering', 'Computer Science Engineering'), ('Information Technology', 'Information Technology'), ('Electronics and Communication Engineering', 'Electronics and Communication Engineering'), ('Electrical and Electronics Engineering', 'Electrical and Electronics Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Biotechnology', 'Biotechnology')], max_length=100),
        ),
    ]
