# Generated by Django 3.2.8 on 2021-10-31 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211031_1628'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_Application',
        ),
    ]
