# Generated by Django 3.2.8 on 2021-10-31 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_student_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='DOB',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
