# Generated by Django 3.2.8 on 2021-10-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contact_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='ssc_memo',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
