# Generated by Django 3.2.8 on 2021-10-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20211031_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='eamcet_score',
            field=models.IntegerField(null=True),
        ),
    ]
