# Generated by Django 3.2.8 on 2021-10-31 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_application_eamcet_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='course',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='ssc_memo',
        ),
    ]
