# Generated by Django 3.2.8 on 2021-11-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20211031_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='course',
            field=models.CharField(choices=[('Artificial Intelligence & Data Science', 'Artificial Intelligence & Data Science'), ('Artificial Intelligence & Machine Learning', 'Artificial Intelligence & Machine Learning'), ('IoT, Block-Chain Technology & Cyber Security', 'IoT, Block-Chain Technology & Cyber Security'), ('Computer Science Engineering', 'Computer Science Engineering'), ('Information Technology', 'Information Technology'), ('Electronics & Communication Engineering', 'Electronics & Communication Engineering'), ('Electrical & Electronics Engineering', 'Electrical & Electronics Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Biotechnology', 'Biotechnology')], max_length=100),
        ),
    ]
